### PR TITLE
Null-cancelling Movement script addon

### PR DESCRIPTION
**Pull request by scrambl-d**

### CODE REVIEW

**Comment by mastercoms** [comment]
How will we bind to the appropriate keys for movement?

**Comment by scrambl-d** [comment]
> How will we bind to the appropriate keys for movement?

Default wasd are bound in the script, if you want to use custom wasd buttons you can bind them to the universally accepted +mfwd etc. from the null cancelling movement addon.

**Comment by mastercoms** [comment]
It seems the null movement script is empty. I feel like if it requires that user specific customization just to set up, it should be left till later, when we have a way to be keybind agnostic.

**Comment by scrambl-d** [comment]
> It seems the null movement script is empty. I feel like if it requires that user specific customization just to set up, it should be left till later, when we have a way to be keybind agnostic.

That's fair, I just assumed that the use case of having different wasd keys was so niche that you could assume they'd be willing to put in the legwork to make it work. If you're planning on having an app to manage keybinds it makes a lot of sense to wait until then. :)

**Review by mastercoms — APPROVED** [review]

**Comment by mastercoms** [comment]
Thank you for your contribution to mastercomfig!

**Pull request merged**
