### PR TITLE
Spy network settings now follows comfig style

### PR DESCRIPTION
**Pull request by Tiagoquix**
https://github.com/mastercoms/mastercomfig/pull/222#issuecomment-594794438

Following the comfig style, I think it should be like this.

### CODE REVIEW

**Comment by Tiagoquix** [comment]
This is not necessary at all, it is only a aesthetic issue.

**Comment by mastercoms** [comment]
I don't understand the benefit of this.

**Comment by Tiagoquix** [comment]
> I don't understand the benefit of this.

It has no benefit, it's just an aesthetic issue like I said. It's just to make it more "organized".

**Comment by mastercoms** [comment]
I feel like it's more confusing, because of the additional alias layer.

**Pull request closed without merging**
