### PR TITLE
An addendum to #430

### PR DESCRIPTION
**Pull request by Tiagoquix**
This modifies the `modules.json` to better corresponds to the current modules page on the docs.
Also, I removed the `"tags": ["advanced"]` from `snapshot_buffer` because it was the only module that was using this, and I don't see a reason to keep it.

Please, only approve and merge this if #430 is merged.

### CODE REVIEW

**Review by mastercoms — CHANGES_REQUESTED** [review]
The changes to advanced should be reverted, as well as the order of snapshot buffer.

**Comment by Tiagoquix** [comment]
> The changes to advanced should be reverted, as well as the order of snapshot buffer.

I will revert the change related to the advanced, but I won't revert the order of snapshot buffer. I am [just listing it the way it's listed in the docs](https://docs.mastercomfig.com/en/latest/customization/modules/#snapshot-buffer).

**Comment by Tiagoquix** [comment]
Done.

**Comment by mastercoms** [comment]
The docs should be changed if you insist.

**Comment by Tiagoquix** [comment]
Done @mastercoms

**Review by mastercoms — APPROVED** [review]

**Pull request merged**
