### PR TITLE
Presets updates

### PR DESCRIPTION
**Pull request by Tiagoquix**
I tweaked it a bit so that each preset really matches its description.

### CODE REVIEW

**Comment by Tiagoquix** [comment]
I also did remove some unnecessary characters from some files. The same what @micwoj92 did, but with more files.

**Review by micwoj92 — COMMENTED** [review]
In surface properties you can also remove quotes

**Comment by micwoj92** [comment]
Also I would left notes, or  at least move them to readme, so someone who needs it, can edit that

**Comment by Tiagoquix** [comment]
> Also I would left notes, or at least move them to readme, so someone who needs it, can edit that

If someone wants to edit, I think the person would read the original file.

**Pull request closed without merging**
