### PR TITLE
Add move_bind to module template, move some other stuff

### PR DESCRIPTION
**Pull request by treacherousfiend**
-Add a Miscellaneous modules section to module template, Logo and Mod Support have been moved there:
-move_bind has been added to this section as well

-Added sound module section in module template to match docs.

### CODE REVIEW

**Comment by micwoj92** [comment]
https://github.com/mastercomfig/mastercomfig/pull/331#pullrequestreview-438752440

**Comment by treacherousfiend** [comment]
dynamic_background is back in HUD, thanks for the link

**Comment by micwoj92** [comment]
Oh, one more thing. Documentation pr's should be made against release branch

**Comment by treacherousfiend** [comment]
alright, i'll remove that from this PR and put in into a new one

**Comment by mastercoms** [comment]
Fixed in 660497b.

**Pull request closed without merging**
