### PR TITLE
Pyroland on all official maps

### PR DESCRIPTION
**Pull request by Tiagoquix**
The mtp.cfg file now contains all (and only) official maps, in alphabetical order. No community maps are included.

**This list also includes the new Christmas maps.**

### CODE REVIEW

**Comment by Tiagoquix** [comment]
For obvious reasons, **background01.bsp** isn't included.

**Comment by mastercoms** [comment]
Some maps are not included because pyroland looks bad on them or does not fit the holiday style (for example halloween maps, since pyroland is technically another type of holiday). Did you actually test on these?

**Comment by Tiagoquix** [comment]
> Some maps are not included because pyroland looks bad on them or does not fit the holiday style (for example halloween maps, since pyroland is technically another type of holiday). Did you actually test on these?

I removed all maps that are themed as:

- **Jungle** (Pyroland doesn't fit the maps' themes)
- **Spytech** (Pyroland doesn't fit the maps' themes)
- **Halloween** (Pyroland doesn't fit the maps' themes)
- **Smissmas** (Pyroland doesn't fit the maps' themes)
- **Snow** (Pyroland doesn't fit the maps' themes)
- **Invasion** (Pyroland doesn't fit the maps' themes)
- **Japanese** (Pyroland doesn't fit the map's theme. **The only Japanese map is Suijin.**)
- **City** (Pyroland doesn't fit the maps' themes)
- **Mann vs. Machine** (Pyroland doesn't fit the maps' themes **+ avoid possible conflicts with RomeVision.**)
- **Space** (Pyroland doesn't fit the map's theme. **The only Space map is Asteroid.**)

I used the TF Wiki maps list for references: https://wiki.teamfortress.com/wiki/List_of_maps

About testing the maps, no, I didn't test them. However, I manually checked each map to see if the map is on the JarateKing's mtp.cfg file. And, all maps that currently are on my mtp.cfg are also present in JarateKing's list. So, I think they are all compatible and do not cause any problems.

You can check his list here: https://raw.githubusercontent.com/JarateKing/jarconfig/master/dev/mtp/raw.txt

**Comment by mastercoms** [comment]
That looks good but just a note, JarateKing's mtp is all maps with no filtering.

**Comment by mastercoms** [comment]
Also, as a note, maps that were specifically removed should not be added again. Those maps were removed for theming reasons or because textures did not fully cover the map.

**Comment by Tiagoquix** [comment]
> Also, as a note, maps that were specifically removed should not be added again. Those maps were removed for theming reasons or because textures did not fully cover the map.

Done.

**Comment by Tiagoquix** [comment]
In the future, if I encounter any problems with any map inside this new mtp.cfg file, I will make a pull request to remove the problematic maps.

**Review by mastercoms — APPROVED** [review]

**Pull request merged**
