### PR TITLE
Changed -gl_nv_bindless_texturing

### PR DESCRIPTION
**Pull request by Sirbucket**
I tested this using

Linux 64bit 5.8.5, Fedora 33
Ryzen 3 3200U
4G of RAM
SSD SATA

Used Medium Low with Lighting_Ex set to high due to seeing graphical errors using mat_phong 0.
mat_dxlevel 92 (OpenGL 3)

Conclusion after using 5 samples from both sides.
4812 frames 57.886 seconds 83.13 fps (12.03 ms/f) 10.753 fps variability
4812 frames 57.857 seconds 83.17 fps (12.02 ms/f) 10.696 fps variability
4812 frames 57.817 seconds 83.23 fps (12.02 ms/f) 11.097 fps variability
4812 frames 57.793 seconds 83.26 fps (12.01 ms/f) 10.886 fps variability
4812 frames 57.862 seconds 83.16 fps (12.02 ms/f) 10.807 fps variability
Bindless Texturing
83.19, 12.02, 10.8478

4812 frames 58.439 seconds 82.34 fps (12.14 ms/f) 11.761 fps variability
4812 frames 57.285 seconds 84.00 fps (11.90 ms/f) 11.149 fps variability
4812 frames 58.032 seconds 82.92 fps (12.06 ms/f) 10.993 fps variability
4812 frames 57.962 seconds 83.02 fps (12.05 ms/f) 10.726 fps variability
4812 frames 58.320 seconds 82.51 fps (12.12 ms/f) 10.794 fps variability
No bindless texturing
82.958, 12.054, 11.0846

On average the fps was more static across all tests with it enabled, without bindless texturing the performance was more variable but had higher potentials to reach better framerates, however on average -gl_nv_bindless_texturing was performing better. As far as I know there are no fps measurement tools on linux so I cannot test a 32 player pl_upward server nor any casual match, data from those would be eyeballed and likely inaccurate. I have no knowledge on how this performs with an intel CPU/GPU nor other combos, for now I'm leaving the tag as experimental with some benchmarks leaning towards it being a positive, I have plans of doing this same testing with -gl_amd_pinned_memory, then once that's complete combining them and seeing the result, if my testing needs more samples/is not capable of being accurate please let me know, from what I know about bindless texturing, it tends to be beneficial and in an artificial test that holds true.

I have no knowledge on if it's source implementation is or isn't complete but work does seem to be there based on the data.

### CODE REVIEW

**Comment by Sirbucket** [comment]
If I need to test with OpenGL 2.1 or need more samples/to find a way to measure in an actual casual match and bot match just point that out and I'll try my best.

**Comment by melvyn2** [comment]
what gpu though

**Comment by Sirbucket** [comment]
Vega 3, iGPU on the CPU

**Comment by micwoj92** [comment]
For me it gives minor boost on rx 560

**Comment by Sirbucket** [comment]
This is my testing data and so far it seems promissing for improving consistent framerates.

**Comment by Sirbucket** [comment]
I spent around 2 hours trying to get a framerate average supported framerate counter to work, thus far I can't get it to work on TF2

**Comment by Sirbucket** [comment]
I do one test run before I start counting it as data to get the system warmed up to simulate longterm usage.

**Comment by Sirbucket** [comment]
The only thing I had open when doing these tests was gedit (Linux Notepad) and the mastercomfig benchmarking page.

**Comment by Sirbucket** [comment]
I was just writing data to it as I went along, didn't alt tab while benchmarks were in progress

**Comment by Sirbucket** [comment]
1920x1080w

**Comment by Sirbucket** [comment]
I was mainly interested in this cause I used to have an even worse laptop with a intel CPU from 2013, sadly its nearly entirely broken and I'd have to go through hell to get it working again, so instead I bought a new one.

**Comment by Sirbucket** [comment]
I have plans of testing the launch options that aren't confirmed to work like -glslmode and see if I can get them to work/find performance impacts depending on what I set.

**Comment by mastercoms** [comment]
Hey, thank you for taking the time to do these benchmarks! Thanks for the detailed report and many benchmarks ran for consistency's sake. However, your benchmarking seems to be too inconclusive to make any changes to the current state of the documentation. Additionally, this is a vendor specific extension, and I doubt AMD cards support it.

**Comment by Sirbucket** [comment]
I don't think nv indicates nvidia fyi, it's called nv_bindless on every platform

**Comment by Sirbucket** [comment]
As far as I know anyways, maybe it is nvidia specific and I'm dumb, but I don't think nvidia would just own the entirety of bindless textures without AMD trying to program an equivalant.

**Comment by Sirbucket** [comment]
Also some things are programmed by a company but aren't company specific, like how intel openimagedenoise isn't only for intel chips and etc.

**Comment by Sirbucket** [comment]
However I do stand by your claim that the benchmarks aren't conclusive enough, I'll run 20 samples each and try and see if I can use replays in community servers and bot matches to record fps.

**Comment by Sirbucket** [comment]
"It is implemented across much of the OpenGL 4.x hardware spectrum. Intel is mostly absent, but both AMD and NVIDIA have a lot of hardware that can handle it." https://www.khronos.org/opengl/wiki/Bindless_Texture#Purpose

My iGPU probably supports it thanks to vega 3, this is where it's actual implementation comes into question though and I am curious, I don't believe this was worth closing yet, I wanted to do a little extra testing before you close it and keep it closed, I can always just make another one once I have more conclusive data though.

**Comment by mastercoms** [comment]
The generic standard is [ARB_bindless_texture](http://www.opengl.org/registry/specs/ARB/bindless_texture.txt) while [NV_bindless_texture](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_bindless_texture.txt) is the vendor extension as you can see in your article that you posted. The NVidia one is not supported by AMD because it uses uint64_t conversion from samplers that are provided by NV_gpu_shader5.

**Comment by Sirbucket** [comment]
Got it, thanks, how come I had weird results with benchmarks on and off then? I'll need to test this a little more to see if it was just placebo or if it actually does something.

**Comment by Sirbucket** [comment]
4812 frames 55.307 seconds 87.00 fps (11.49 ms/f) 11.845 fps variability
4812 frames 55.427 seconds 86.82 fps (11.52 ms/f) 11.240 fps variability
4812 frames 56.247 seconds 85.55 fps (11.69 ms/f) 11.034 fps variability
4812 frames 56.286 seconds 85.49 fps (11.70 ms/f) 11.143 fps variability
4812 frames 57.215 seconds 84.10 fps (11.89 ms/f) 10.818 fps variability
4812 frames 56.922 seconds 84.54 fps (11.83 ms/f) 10.848 fps variability
4812 frames 57.160 seconds 84.18 fps (11.88 ms/f) 10.679 fps variability
4812 frames 56.969 seconds 84.47 fps (11.84 ms/f) 10.785 fps variability
4812 frames 56.911 seconds 84.55 fps (11.83 ms/f) 11.082 fps variability
4812 frames 56.997 seconds 84.43 fps (11.84 ms/f) 10.776 fps variability
4812 frames 57.623 seconds 83.51 fps (11.97 ms/f) 10.844 fps variability
4812 frames 57.022 seconds 84.39 fps (11.85 ms/f) 11.090 fps variability
4812 frames 57.405 seconds 83.83 fps (11.93 ms/f) 10.675 fps variability
4812 frames 57.213 seconds 84.11 fps (11.89 ms/f) 10.623 fps variability
4812 frames 57.418 seconds 83.81 fps (11.93 ms/f) 10.841 fps variability
4812 frames 57.349 seconds 83.91 fps (11.92 ms/f) 10.809 fps variability
4812 frames 57.187 seconds 84.15 fps (11.88 ms/f) 10.791 fps variability
4812 frames 57.473 seconds 83.73 fps (11.94 ms/f) 10.662 fps variability
4812 frames 57.540 seconds 83.63 fps (11.96 ms/f) 10.765 fps variability
4812 frames 57.754 seconds 83.32 fps (12.00 ms/f) 10.652 fps variability
Bindless Texturing
84.48, 11.84, 10.902

4812 frames 55.942 seconds 86.02 fps (11.63 ms/f) 11.530 fps variability
4812 frames 55.640 seconds 86.48 fps (11.56 ms/f) 11.371 fps variability
4812 frames 55.559 seconds 86.61 fps (11.55 ms/f) 11.451 fps variability
4812 frames 56.554 seconds 85.09 fps (11.75 ms/f) 11.293 fps variability
4812 frames 56.564 seconds 85.07 fps (11.75 ms/f) 11.238 fps variability
4812 frames 56.562 seconds 85.07 fps (11.75 ms/f) 11.103 fps variability
4812 frames 56.479 seconds 85.20 fps (11.74 ms/f) 11.103 fps variability
4812 frames 56.836 seconds 84.67 fps (11.81 ms/f) 11.147 fps variability
4812 frames 56.320 seconds 85.44 fps (11.70 ms/f) 11.191 fps variability
4812 frames 56.464 seconds 85.22 fps (11.73 ms/f) 11.334 fps variability
4812 frames 56.722 seconds 84.83 fps (11.79 ms/f) 11.315 fps variability
4812 frames 56.966 seconds 84.47 fps (11.84 ms/f) 11.117 fps variability
4812 frames 57.047 seconds 84.35 fps (11.86 ms/f) 11.177 fps variability
4812 frames 56.418 seconds 85.29 fps (11.72 ms/f) 11.502 fps variability
4812 frames 57.136 seconds 84.22 fps (11.87 ms/f) 11.279 fps variability
4812 frames 56.527 seconds 85.13 fps (11.75 ms/f) 11.333 fps variability
4812 frames 56.840 seconds 84.66 fps (11.81 ms/f) 11.166 fps variability
4812 frames 56.889 seconds 84.59 fps (11.82 ms/f) 11.270 fps variability
4812 frames 56.928 seconds 84.53 fps (11.83 ms/f) 11.300 fps variability
4812 frames 56.741 seconds 84.81 fps (11.79 ms/f) 11.163 fps variability
4812 frames 56.663 seconds 84.92 fps (11.78 ms/f) 11.249 fps variability
Non Binding
85.09, 11.75, 11.269

Now it seems like having it enabled negatively impacts devices that don't support it, or it's placebo and it's within margin of error.

**Comment by Sirbucket** [comment]
Gonna test -gl_amd_pinned_memory though (I assume this isn't restricted to amd devices considering usually amd implemented features work for intel too.)

**Pull request closed without merging**
