### PR TITLE
Don't force  party join request mode

### PR DESCRIPTION
**Pull request by micwoj92**
Don't force  party join request mode

### CODE REVIEW

**Comment by Tiagoquix** [comment]
I do not agree with this change. It is annoying that anyone could join your party without asking if they could join in the first place.
CS:GO's default, if I'm not mistaken, is a "ask-first-permission" to join someone's party.

**Comment by micwoj92** [comment]
Mastercomfig should not change settings which do not matter for performance. You can check that many changes in recent months were like this. I will repeat what I said in #360 "Keeping in line with the new approach to mastercomfig defaults, the default for the downloads module should not be set." Just replace download module with party join request mode.

**Comment by micwoj92** [comment]
image
This is what mastercoms said about this

**Comment by micwoj92** [comment]
Also please do not comment on my prs unless you unblock me so I can comment on yours, thanks.

**Comment by Tiagoquix** [comment]
Your reason for making this change is valid, but I still don't agree with the change.

**Comment by mastercoms** [comment]
This is a change made for security reasons as someone who joins your party can spam party chat.

**Comment by melvyn2** [comment]
I find this quite annoying, as I have to change it at launch every time, at least until I found the command and the cause. It would be better for it to be marked somewhere that this option is set by default, and have an option to disable it.

**Comment by mastercoms** [comment]
I would be open to a module for this option.

**Comment by Tiagoquix** [comment]
> I find this quite annoying, as I have to change it at launch every time, at least until I found the command and the cause. It would be better for it to be marked somewhere that this option is set by default, and have an option to disable it.

Fixed in #455

**Pull request closed without merging**
