### PR TITLE
How to install mastercomfig - russian translation

### PR DESCRIPTION
**Pull request by Maurvick**

### CODE REVIEW

**Comment by micwoj92** [comment]
I think that the index file is needed

**Comment by Maurvick** [comment]
> I think that the index file is needed

but it only has one line

**Comment by micwoj92** [comment]
Try to make website without index, I dare you!

**Comment by Winth211** [comment]
> Try to make website without index, I dare you!

And then what should I replace instead of index.md?
install.md?

**Comment by Maurvick** [comment]
> Try to make website without index, I dare you!

And then what should I replace instead of index.md?
install.md?

**Comment by micwoj92** [comment]
No. What I am trying to say is that you need index.

**Comment by micwoj92** [comment]
be it index.html, php or md

**Comment by mastercoms** [comment]
Translate index.md to index.ru.md

**Pull request closed without merging**
