### PR TITLE
Clarify HUD avatars only works with floating health bars

### PR DESCRIPTION
**Pull request by Tiagoquix**

### CODE REVIEW

**Review by mastercoms — APPROVED** [review]

**Review by mastercoms — DISMISSED** [review]

**Comment by mastercoms** [comment]
They also show in the scoreboard.

**Comment by Tiagoquix** [comment]
> They also show in the scoreboard.

This is irrelevant to this module, because HUD avatars only affect **Target ID** (i.e. mouse over a player to see their nickname and photo). On the scoreboard, the avatars are always shown (even if HUD avatars are disabled).

Floating health bars are enabled by default, but can be disabled, and when disabled, they hide the avatars.

**Comment by mastercoms** [comment]
Yes, but when you say it like in the PR, I think confusion comes up, what it says right now with just saying it's target ID avatars, it's clear enough.

**Comment by Tiagoquix** [comment]
Sure, I'll do another PR to make it more clear.

**Comment by mastercoms** [comment]
It's already clear: it says it controls the display of avatars for target ID. When you add an additional condition for when it "controls" that, then people can get confused.

**Comment by Tiagoquix** [comment]
Yes, but the target ID avatars aren't displayed when floating health bars are enabled.

**Comment by Tiagoquix** [comment]
I see. We could rephrase it as:

"Controls the display of target ID avatars. Target ID only works when floating health bars are enabled."

**Pull request closed without merging**
