### PR TITLE
Add Windows launch options list

### PR DESCRIPTION
**Pull request by Leo40Git**

### CODE REVIEW

**Comment by mastercoms** [comment]
Which folder did you select? This doesn't seem like everything.

**Comment by Leo40Git** [comment]
`C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2`

**Comment by mastercoms** [comment]
Doesn't it separate by dll/exe? Which files did you choose from? It's alright if there's some junk, humans can read it and figure out the valid ones.

**Comment by Leo40Git** [comment]
Pretty much all of these are from engine.dll. `-nostartupsound` came from GameUI.dll (the rest of GameUI.dll were garbage or duplicates).

**Comment by mastercoms** [comment]
Could you upload the full file?

**Comment by Leo40Git** [comment]
https://gist.github.com/Leo40Git/1e3cfd09dd8114518ef5b19e391d8133

**Comment by mastercoms** [comment]
https://gist.github.com/mastercoms/d9485d89e5e55d74ab705790f40c9e66

**Comment by Leo40Git** [comment]
DON'T MERGE YET, wanna do something real quick

**Comment by Leo40Git** [comment]
okay you can merge now

**Review by mastercoms — APPROVED** [review]

**Comment by mastercoms** [comment]
Thank you for your contribution to mastercomfig!

**Pull request merged**
