### PR TITLE
Spy interp/snapshot buffer

### PR DESCRIPTION
**Pull request by Tiagoquix**
That was wrong, I did only the basic and removed the values for you setting these later.

### CODE REVIEW

**Comment by mastercoms** [comment]
Sorry, I'm not sure what this is for.

**Comment by Tiagoquix** [comment]
> Sorry, I'm not sure what this is for.

Following the comfig style, `interp_standard/congestion_*` should not set `cl_interp_ratio`, and `snapshot_buffer_spy` should set the `cl_interp_ratio` value.

**Comment by Tiagoquix** [comment]
I did only made the base for you to finish later.

**Comment by mastercoms** [comment]
It should in this case, as congestion does not need a lower interp to be safe for server framerate drops.

**Pull request closed without merging**
