### PR TITLE
Added VRR to windows.md

### PR DESCRIPTION
**Pull request by Sirbucket**
Variable refresh rate is now a baseline feature if your GPU supports it, you can find it in the same menu as Hardware-accelerated GPU scheduling.

### CODE REVIEW

**Comment by Sirbucket** [comment]
I noticed this in my graphics menu after the most recent creators update, so I put it here.

**Comment by Sirbucket** [comment]
For confirmation 
VRR
https://www.techspot.com/news/80369-microsoft-adds-variable-refresh-rate-setting-windows-10.html

**Comment by Sirbucket** [comment]
The article is slightly outdated as the current iteration works for all game platforms unlike the version initially released which only supported MS store games.

**Comment by mastercoms** [comment]
Are you sure this works with the DX9 frame submission that TF2 uses? (i.e. no DXGI, no multiple swapchains)

**Comment by mastercoms** [comment]
I am going to close this, as it will not work with TF2.

> This new toggle enables VRR support for DX11 full-screen games that did not support VRR natively, so these games can now benefit from your VRR hardware.

https://devblogs.microsoft.com/directx/os-variable-refresh-rate/

**Pull request closed without merging**
