### PR TITLE
Made hr.cfg

### PR DESCRIPTION
**Pull request by AeroGH**
Its done.

### CODE REVIEW

**Comment by mastercoms** [comment]
Could you add hr to `config/mastercomfig/cfg/comfig/define_langs.cfg`?

**Comment by AeroGH** [comment]
> Could you add hr to `config/mastercomfig/cfg/comfig/define_langs.cfg`?

Done

**Comment by micwoj92** [comment]
You could do it in the same pull request.

**Review by mastercoms — APPROVED** [review]

**Comment by AeroGH** [comment]
I am sorry,I am not used to using github as a whole

**Comment by mastercoms** [comment]
It's alright, I can accommodate. Next time, you can click your branch and then edit the file in there.

branch

**Pull request merged**
